--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      DATA MODEL
--
-- Date Created : Tuesday, February 11, 2025 19:12:49
-- Target DBMS : Oracle 19c
--

-- 
-- TABLE: ADR 
--

CREATE TABLE ADR(
    ADR_ID      CHAR(10)    NOT NULL,
    ADR_LN_1    CHAR(10),
    ADR_LN_2    CHAR(10),
    CTY         CHAR(10),
    PST_CDE     CHAR(10),
    CTY_1       CHAR(10),
    PRIMARY KEY (ADR_ID)
)
;



-- 
-- TABLE: AGY 
--

CREATE TABLE AGY(
    ID          CHAR(10)    NOT NULL,
    AGY_NME     CHAR(10),
    MAIN_CCT    CHAR(10),
    CONTRACT    CHAR(10),
    PRIMARY KEY (ID)
)
;



-- 
-- TABLE: CNR 
--

CREATE TABLE CNR(
    EMP_NMB     CHAR(10)    NOT NULL,
    DAY_RAT     CHAR(10),
    AGENCYID    CHAR(10)    NOT NULL,
    PRIMARY KEY (EMP_NMB)
)
;



-- 
-- TABLE: DEP 
--

CREATE TABLE DEP(
    ID     CHAR(10)    NOT NULL,
    NME    CHAR(10),
    PRIMARY KEY (ID)
)
;



-- 
-- TABLE: EMP 
--

CREATE TABLE EMP(
    EMP_NMB      CHAR(10)         NOT NULL,
    EMP_TYP      CHAR(1)          NOT NULL,
    STT_DTE      DATE,
    PHONE_NMB    NUMBER(15, 0),
    FRS_NME      CHAR(10)         NOT NULL,
    SURNAME      CHAR(10)         NOT NULL,
    MEMBER       CHAR(10)         NOT NULL,
    MANAGER      CHAR(10),
    ADR_ID       CHAR(10)         NOT NULL,
    PRIMARY KEY (EMP_NMB)
)
;



-- 
-- TABLE: EMP_SKL_MTX 
--

CREATE TABLE EMP_SKL_MTX(
    ID         CHAR(10)    NOT NULL,
    EMP_NMB    CHAR(10)    NOT NULL,
    LVL        CHAR(10),
    PRIMARY KEY (ID, EMP_NMB)
)
;



-- 
-- TABLE: FULL_TIME_EMP 
--

CREATE TABLE FULL_TIME_EMP(
    EMP_NMB     CHAR(10)    NOT NULL,
    SALARY      CHAR(10),
    VCT_DAYS    CHAR(10),
    PRIMARY KEY (EMP_NMB)
)
;



-- 
-- TABLE: SKL 
--

CREATE TABLE SKL(
    ID     CHAR(10)    NOT NULL,
    NME    CHAR(10)    NOT NULL,
    DSP    CHAR(10),
    CTY    CHAR(10),
    PRIMARY KEY (ID)
)
;



-- 
-- TABLE: "SKL TRG_CRS" 
--

CREATE TABLE "SKL TRG_CRS"(
    ID        CHAR(10)    NOT NULL,
    CRS_ID    CHAR(10)    NOT NULL,
    PRIMARY KEY (ID, CRS_ID)
)
;



-- 
-- TABLE: TRG_CRS 
--

CREATE TABLE TRG_CRS(
    CRS_ID      CHAR(10)    NOT NULL,
    TITLE       CHAR(10),
    SYNOPSIS    CHAR(10),
    PRIMARY KEY (CRS_ID)
)
;



-- 
-- TABLE: TRG_HST 
--

CREATE TABLE TRG_HST(
    EMP_NMB           CHAR(10)    NOT NULL,
    CRS_ID            CHAR(10)    NOT NULL,
    COMPLETION_DTE    CHAR(10),
    RESULT            CHAR(10),
    PRIMARY KEY (EMP_NMB, CRS_ID)
)
;



-- 
-- TABLE: CNR 
--

ALTER TABLE CNR ADD CONSTRAINT FK10 
    FOREIGN KEY (AGENCYID)
    REFERENCES AGY(ID)
;

ALTER TABLE CNR ADD CONSTRAINT FK21 
    FOREIGN KEY (EMP_NMB)
    REFERENCES EMP(EMP_NMB)
;


-- 
-- TABLE: EMP 
--

ALTER TABLE EMP ADD CONSTRAINT FK7 
    FOREIGN KEY (ADR_ID)
    REFERENCES ADR(ADR_ID)
;

ALTER TABLE EMP ADD CONSTRAINT FK8 
    FOREIGN KEY (MANAGER)
    REFERENCES DEP(ID)
;

ALTER TABLE EMP ADD CONSTRAINT FK9 
    FOREIGN KEY (MEMBER)
    REFERENCES DEP(ID)
;


-- 
-- TABLE: EMP_SKL_MTX 
--

ALTER TABLE EMP_SKL_MTX ADD CONSTRAINT RefAGY141 
    FOREIGN KEY (ID)
    REFERENCES AGY(ID)
;

ALTER TABLE EMP_SKL_MTX ADD CONSTRAINT RefCNR161 
    FOREIGN KEY (EMP_NMB)
    REFERENCES CNR(EMP_NMB)
;

ALTER TABLE EMP_SKL_MTX ADD CONSTRAINT RefDEP181 
    FOREIGN KEY (ID)
    REFERENCES DEP(ID)
;

ALTER TABLE EMP_SKL_MTX ADD CONSTRAINT RefFULL_TIME_EMP201 
    FOREIGN KEY (EMP_NMB)
    REFERENCES FULL_TIME_EMP(EMP_NMB)
;

ALTER TABLE EMP_SKL_MTX ADD CONSTRAINT FK5 
    FOREIGN KEY (ID)
    REFERENCES SKL(ID)
;

ALTER TABLE EMP_SKL_MTX ADD CONSTRAINT FK6 
    FOREIGN KEY (EMP_NMB)
    REFERENCES EMP(EMP_NMB)
;


-- 
-- TABLE: FULL_TIME_EMP 
--

ALTER TABLE FULL_TIME_EMP ADD CONSTRAINT FK20 
    FOREIGN KEY (EMP_NMB)
    REFERENCES EMP(EMP_NMB)
;


-- 
-- TABLE: "SKL TRG_CRS" 
--

ALTER TABLE "SKL TRG_CRS" ADD CONSTRAINT RefAGY131 
    FOREIGN KEY (ID)
    REFERENCES AGY(ID)
;

ALTER TABLE "SKL TRG_CRS" ADD CONSTRAINT RefDEP171 
    FOREIGN KEY (ID)
    REFERENCES DEP(ID)
;

ALTER TABLE "SKL TRG_CRS" ADD CONSTRAINT RefSKL22 
    FOREIGN KEY (ID)
    REFERENCES SKL(ID)
;

ALTER TABLE "SKL TRG_CRS" ADD CONSTRAINT RefTRG_CRS23 
    FOREIGN KEY (CRS_ID)
    REFERENCES TRG_CRS(CRS_ID)
;


-- 
-- TABLE: TRG_HST 
--

ALTER TABLE TRG_HST ADD CONSTRAINT RefCNR151 
    FOREIGN KEY (EMP_NMB)
    REFERENCES CNR(EMP_NMB)
;

ALTER TABLE TRG_HST ADD CONSTRAINT RefEMP191 
    FOREIGN KEY (EMP_NMB)
    REFERENCES EMP(EMP_NMB)
;

ALTER TABLE TRG_HST ADD CONSTRAINT FK3 
    FOREIGN KEY (CRS_ID)
    REFERENCES TRG_CRS(CRS_ID)
;

ALTER TABLE TRG_HST ADD CONSTRAINT FK_1 
    FOREIGN KEY (EMP_NMB)
    REFERENCES FULL_TIME_EMP(EMP_NMB)
;


