--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      Snowflake123_new
--
-- Date Created : Thursday, January 23, 2025 14:23:53
-- Target DBMS : Snowflake
--

-- 
-- TABLE: ADR 
--

CREATE TABLE ADR(
    ADRID       INTEGER         IDENTITY(1,1),
    ADRLINE1    VARCHAR(100)    NOT NULL,
    ADRLINE2    VARCHAR(100),
    CITY        VARCHAR(100),
    POSTCDE     VARCHAR(10),
    CTY         VARCHAR(4),
    CONSTRAINT PK4 PRIMARY KEY (ADRID) 
)
;



-- 
-- TABLE: AGY 
--

CREATE TABLE AGY(
    ID          INTEGER          IDENTITY(1,1),
    AGYNME      VARCHAR(10),
    MAINCCT     VARCHAR(100),
    CONTRACT    VARCHAR(1000),
    CONSTRAINT PK9 PRIMARY KEY (ID) 
)
;



-- 
-- TABLE: CNR 
--

CREATE TABLE CNR(
    EMPNMB      VARCHAR(12)     NOT NULL,
    DAYRAT      NUMBER(7, 0),
    AGENCYID    INTEGER         NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (EMPNMB) 
)
;



-- 
-- TABLE: DEP 
--

CREATE TABLE DEP(
    ID     CHAR(10)    NOT NULL,
    NME    CHAR(10),
    CONSTRAINT PK7 PRIMARY KEY (ID) 
)
;



-- 
-- TABLE: EMP 
--

CREATE TABLE EMP(
    EMPNMB      VARCHAR(12)      NOT NULL,
    EMPTYP      CHAR(1)          NOT NULL,
    STTDTE      DATE,
    PHONENMB    NUMBER(15, 0),
    FRSNME      VARCHAR(200)     NOT NULL,
    SURNAME     VARCHAR(200)     NOT NULL,
    MEMBER      CHAR(10)         NOT NULL,
    MANAGER     CHAR(10),
    ADRID       INTEGER          NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (EMPNMB) 
)
;



-- 
-- TABLE: EMPSKLMTX 
--

CREATE TRANSIENT TABLE EMPSKLMTX(
    ID        CHAR(10)       NOT NULL,
    EMPNMB    VARCHAR(12)    NOT NULL,
    LVL       CHAR(10),
    CONSTRAINT PK13 PRIMARY KEY (ID, EMPNMB) 
)
CLUSTER BY(ID) 
;



-- 
-- TABLE: FULL_TIMEEMP 
--

CREATE TABLE FULL_TIMEEMP(
    EMPNMB     VARCHAR(12)    NOT NULL,
    SALARY     REAL,
    VCTDAYS    INTEGER,
    CONSTRAINT PK2 PRIMARY KEY (EMPNMB) 
)
;



-- 
-- TABLE: SKL 
--

CREATE TABLE SKL(
    ID     CHAR(10)    NOT NULL,
    NME    CHAR(10)    NOT NULL,
    DSP    CHAR(10),
    CTY    CHAR(10),
    CONSTRAINT PK5 PRIMARY KEY (ID) 
)
;



-- 
-- TABLE: "SKL TRGCRS" 
--

CREATE TABLE "SKL TRGCRS"(
    ID       CHAR(10)    NOT NULL,
    CRSID    CHAR(10)    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (ID, CRSID) 
)
;



-- 
-- TABLE: TEST_TEXT 
--

CREATE TABLE TEST_TEXT(
    V      TEXT,
    V50    TEXT(50),
    C      TEXT(1),
    C10    TEXT(10),
    S      TEXT,
    S20    TEXT(20),
    T      TEXT,
    T31    TIMESTAMP_LTZ
)
DATA_RETENTION_TIME_IN_DAYS = 1 
;



-- 
-- TABLE: TRGCRS 
--

CREATE TABLE TRGCRS(
    CRSID       CHAR(10)    NOT NULL,
    TITLE       CHAR(10),
    SYNOPSIS    CHAR(10),
    CONSTRAINT PK8 PRIMARY KEY (CRSID) 
)
;



-- 
-- TABLE: TRGHST 
--

CREATE TABLE TRGHST(
    EMPNMB           VARCHAR(12)    NOT NULL,
    CRSID            CHAR(10)       NOT NULL,
    COMPLETIONDTE    CHAR(10),
    RESULT           CHAR(10),
    CONSTRAINT PK12 PRIMARY KEY (EMPNMB, CRSID) 
)
;



-- 
-- TABLE: CNR 
--

ALTER TABLE CNR ADD CONSTRAINT FK 
    FOREIGN KEY (EMPNMB)
    REFERENCES EMP(EMPNMB)
;

ALTER TABLE CNR ADD CONSTRAINT FK2 
    FOREIGN KEY (AGENCYID)
    REFERENCES AGY(ID)
;


-- 
-- TABLE: EMP 
--

ALTER TABLE EMP ADD CONSTRAINT FK1 
    FOREIGN KEY (ADRID)
    REFERENCES ADR(ADRID)
;

ALTER TABLE EMP ADD CONSTRAINT FK3 
    FOREIGN KEY (MANAGER)
    REFERENCES DEP(ID)
;

ALTER TABLE EMP ADD CONSTRAINT FK4 
    FOREIGN KEY (MEMBER)
    REFERENCES DEP(ID)
;


-- 
-- TABLE: EMPSKLMTX 
--

ALTER TABLE EMPSKLMTX ADD CONSTRAINT FK5 
    FOREIGN KEY (EMPNMB)
    REFERENCES EMP(EMPNMB)
;

ALTER TABLE EMPSKLMTX ADD CONSTRAINT FK7 
    FOREIGN KEY (ID)
    REFERENCES SKL(ID)
;


-- 
-- TABLE: FULL_TIMEEMP 
--

ALTER TABLE FULL_TIMEEMP ADD CONSTRAINT FK_1 
    FOREIGN KEY (EMPNMB)
    REFERENCES EMP(EMPNMB)
;


-- 
-- TABLE: "SKL TRGCRS" 
--

ALTER TABLE "SKL TRGCRS" ADD CONSTRAINT RefTRGCRS26 
    FOREIGN KEY (CRSID)
    REFERENCES TRGCRS(CRSID)
;

ALTER TABLE "SKL TRGCRS" ADD CONSTRAINT RefSKL8 
    FOREIGN KEY (ID)
    REFERENCES SKL(ID)
;


-- 
-- TABLE: TRGHST 
--

ALTER TABLE TRGHST ADD CONSTRAINT FK6 
    FOREIGN KEY (EMPNMB)
    REFERENCES FULL_TIMEEMP(EMPNMB)
;

ALTER TABLE TRGHST ADD CONSTRAINT FK9 
    FOREIGN KEY (CRSID)
    REFERENCES TRGCRS(CRSID)
;


